spring:
  spring:
    cloud:
      gateway:
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "https://convomate.netlify.app,https://convomate.duckdns.org"
              allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600

  # Other application configurations...
  datasource:
    url: jdbc:postgresql://localhost:5432/convomant
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: convomate.contact@gmail.com
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
    from:
      name: Convomate

security:
  jwt:
    secret-key: <key>
    expiration-time: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
python:
  flask:
    translate-url: http://127.0.0.1:5000/translate
    correct-text-url: http://127.0.0.1:5001/correct_text
    summarizer-url: http://127.0.0.1:5002/summarize
    chat-url: http://127.0.0.1:5003/chat
    chat-start-url: http://127.0.0.1:5003/start